trapper/trapper-project/trapper/apps/media_classification/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import include
from django.urls import reverse_lazy, path, re_path
from django.views.generic import RedirectView
from rest_framework.routers import DefaultRouter

import trapper.apps.media_classification.views.ai_classifications
from trapper.apps.media_classification.views import (
    api as classification_api_views,
    classifications as classifications_views,
    user_classifications as user_classifications_views,
    ai_classifications as ai_classifications_views,
    projects as projects_views,
    classificators as classificators_views,
    sequences as sequences_views,
    jupyter_hub as jupyter_hub_views,
)

app_name = "media_classification"

router = DefaultRouter(trailing_slash=False)

router.register(
    r"classificators",
    classification_api_views.ClassificatorViewSet,
    basename="api-classificator",
)

router.register(
    r"user-classifications",
    classification_api_views.UserClassificationViewSet,
    basename="api-user-classification",
)

router.register(
    r"classifications",
    classification_api_views.ClassificationViewSet,
    basename="api-classification",
)

router.register(
    r"ai-classifications",
    classification_api_views.AIClassificationViewSet,
    basename="api-ai-classification",
)

router.register(
    r"classifications_map",
    classification_api_views.ClassificationMapViewSet,
    basename="api-classification-map",
)

router.register(
    r"projects",
    classification_api_views.ClassificationProjectViewSet,
    basename="api-classification-project",
)

router.register(
    r"project/(?P<project_pk>\d+)/collections",
    classification_api_views.ClassificationProjectCollectionViewSet,
    basename="api-classification-project-collection",
)

router.register(
    r"sequences", classification_api_views.SequenceViewSet, basename="api-sequence"
)

router.register(
    r"collection/(?P<collection_pk>\d+)/resources/$",
    classification_api_views.ClassificationResourcesViewSet,
    basename="api-classification-resources",
)

urlpatterns = [
    re_path(r"^api/", include(router.urls)),
    re_path(
        r"^api/classifications/results/(?P<project_pk>\d+)/",
        classification_api_views.ClassificationResultsView.as_view(),
        name="api-classification-results",
    ),
    re_path(
        r"^api/ai-classifications/results/(?P<project_pk>\d+)/",
        classification_api_views.AIClassificationResultsView.as_view(),
        name="api-ai-classification-results",
    ),
    re_path(
        r"^api/classifications/results/agg/(?P<project_pk>\d+)/",
        classification_api_views.ClassificationResultsAggView.as_view(),
        name="api-classification-results-agg",
    ),
    re_path(
        r"^api/classifications/import/",
        classification_api_views.ClassificationImport.as_view(),
        name="api-classification-import",
    ),
    re_path(
        r"^api/media/(?P<project_pk>\d+)/",
        classification_api_views.ClassificationProjectMediaTableView.as_view(),
        name="api-media-export",
    ),
    re_path(
        r"^api/package/(?P<project_pk>\d+)/",
        classification_api_views.ResultsDataPackageAPIView.as_view(),
        name="api-package-export",
    ),
    path(
        "api/classify/ai/callback/<str:ai_provider_token>/",
        classification_api_views.classify_ai_callback,
        name="api-classify-ai-callback",
    ),
    path(
        "api/classify/ai/classification_extra/<str:ai_provider_token>/<str:classification_job_id>/<str:resource_name>/",
        classification_api_views.classify_ai_extra_resource,
        name="api-classify-ai-extra",
    ),
]

urlpatterns += [
    re_path(
        r"^$",
        RedirectView.as_view(url=reverse_lazy("media_classification:project_list")),
        name="project_index",
    ),
    # Project views
    re_path(r"project/list/$", projects_views.view_project_list, name="project_list"),
    re_path(
        r"project/detail/(?P<pk>\d+)/$",
        projects_views.view_project_detail,
        name="project_detail",
    ),
    re_path(
        r"project/create/$", projects_views.view_project_create, name="project_create"
    ),
    re_path(
        r"project/update/(?P<pk>\d+)/$",
        projects_views.view_project_update,
        name="project_update",
    ),
    re_path(
        r"project/delete/(?P<pk>\d+)/$",
        projects_views.view_project_delete,
        name="project_delete",
    ),
    re_path(
        r"^project/delete/$",
        projects_views.view_project_delete,
        name="project_delete_multiple",
    ),
    re_path(
        r"project/collection/add/$",
        projects_views.view_project_collection_add,
        name="project_collection_add",
    ),
    re_path(
        r"project/collection/delete/(?P<pk>\d+)/$",
        projects_views.view_project_collection_delete,
        name="project_collection_delete",
    ),
    re_path(
        r"^project/collection/delete/$",
        projects_views.view_project_collection_delete,
        name="project_collection_delete_multiple",
    ),
    re_path(
        r"^project/collection/blur/$",
        projects_views.view_project_collection_blur_humans,
        name="project_collection_blur_humans",
    ),
    # Classificator views
    re_path(
        r"classificator/list/$",
        classificators_views.view_classificator_list,
        name="classificator_list",
    ),
    re_path(
        r"classificator/detail/(?P<pk>\d+)/$",
        classificators_views.view_classificator_detail,
        name="classificator_detail",
    ),
    re_path(
        r"classificator/create/$",
        classificators_views.view_classificator_create,
        name="classificator_create",
    ),
    re_path(
        r"classificator/update/(?P<pk>\d+)/$",
        classificators_views.view_classificator_update,
        name="classificator_update",
    ),
    re_path(
        r"classificator/clone/(?P<pk>\d+)/$",
        classificators_views.view_classificator_clone,
        name="classificator_clone",
    ),
    re_path(
        r"^classificator/delete/(?P<pk>\d+)/$",
        classificators_views.view_classificator_delete,
        name="classificator_delete",
    ),
    re_path(
        r"^classificator/delete/$",
        classificators_views.view_classificator_delete,
        name="classificator_delete_multiple",
    ),
    # Sequence views
    re_path(
        r"sequence/create/$",
        sequences_views.view_sequence_change,
        name="sequence_create",
    ),
    re_path(
        r"sequence/update/$",
        sequences_views.view_sequence_change,
        name="sequence_update",
    ),
    re_path(
        r"sequence/change/$",
        sequences_views.view_sequence_change,
        name="sequence_change",
    ),
    re_path(
        r"sequence/delete/$",
        sequences_views.view_sequence_delete,
        name="sequence_delete",
    ),
    re_path(
        r"^sequence/build/$", sequences_views.view_sequence_build, name="sequence_build"
    ),
    # Classification views
    re_path(
        r"^classification/overview/$",
        classifications_views.view_classification_overview,
        name="classification_overview",
    ),
    re_path(
        r"^classification/list/(?P<pk>\d+)/$",
        classifications_views.view_classification_list,
        name="classification_list",
    ),
    re_path(
        r"classification/import/$",
        classifications_views.view_classification_import,
        name="classification_import",
    ),
    re_path(
        r"classification/import/(?P<pk>\d+)/$",
        classifications_views.view_classification_import,
        name="classification_import",
    ),
    re_path(
        r"classification/export/(?P<pk>\d+)/$",
        classifications_views.view_classification_export,
        name="classification_export",
    ),
    re_path(
        r"classification/publish/$",
        classifications_views.view_classification_publish,
        name="classification_publish",
    ),
    re_path(
        r"classification/feedback/(?P<pk>\d+)/$",
        classifications_views.view_classification_feedback,
        name="classification_feedback",
    ),
    re_path(
        r"classification/export-agg/(?P<pk>\d+)/$",
        classifications_views.view_classification_export_agg,
        name="classification_export_agg",
    ),
    re_path(
        r"classification/importattrs/(?P<pk>\d+)/$",
        classifications_views.view_classification_import_attrs,
        name="classification_importattrs",
    ),
    re_path(
        r"^classification/delete/(?P<pk>\d+)/$",
        classifications_views.view_classification_delete,
        name="classification_delete",
    ),
    re_path(
        r"^classification/delete/$",
        classifications_views.view_classification_delete,
        name="classification_delete_multiple",
    ),
    re_path(
        r"^classification/bulk-update/$",
        classifications_views.view_classification_bulk_update,
        name="classification_bulk_update",
    ),
    re_path(
        r"classify/(?P<project_pk>\d+)/(?P<collection_pk>\d+)/$",
        classifications_views.view_classify_collection,
        name="classify_collection",
    ),
    re_path(
        r"classify/(?P<pk>\d+)/$",
        classifications_views.view_classify_resource,
        name="classify",
    ),
    re_path(
        r"classify/(?P<pk>\d+)/user/(?P<user_pk>\d+)/$",
        classifications_views.view_classify_resource,
        name="classify_user",
    ),
    re_path(
        r"classify/form/(?P<project_pk>\d+)/$",
        classifications_views.view_classify_form,
        name="classify_form",
    ),
    re_path(
        r"classify/form/(?P<project_pk>\d+)/(?P<classification_pk>\d+)/$",
        classifications_views.view_classify_form,
        name="classify_form",
    ),
    re_path(
        r"classify/form/(?P<project_pk>\d+)/(?P<classification_pk>\d+)/(?P<user_pk>\d+)/$",
        classifications_views.view_classify_form,
        name="classify_form",
    ),
    path(

trapper/trapper-project/trapper/urls.py
# -*- coding: utf-8 -*-
import debug_toolbar
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, reverse_lazy, re_path
from django.views.decorators.cache import cache_control, cache_page, never_cache
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.generic import RedirectView
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions
from trapper.apps.accounts.views import accounts as accounts_views
from umap import views as umap_views
from umap.decorators import (
    map_permissions_check,
    login_required_if_not_anonymous_allowed,
)
from umap.utils import decorated_patterns

admin.autodiscover()


swagger_schema_view = get_schema_view(
    openapi.Info(
        title="TRAPPER API",
        default_version="v1",
        description="",
        terms_of_service="terms of service",
        contact=openapi.Contact(email="contact@os-conservation.org"),
        # license=openapi.License(name="BSD License"),
    ),
    public=False,
    permission_classes=[permissions.IsAuthenticated],
)


api_patterns = [
    path("accounts/", include("trapper.apps.accounts.urls_rest")),
    path("cs/", include("trapper.apps.citizen_science.urls_rest")),
    path("deployments/", include("trapper.apps.geomap.urls_rest")),
    path(
        "media-classifications/", include("trapper.apps.media_classification.urls_rest")
    ),
    path("teams/", include("trapper.apps.teams.urls_rest")),
]


urlpatterns = [
    # Overrides
    # Overwrite account inactive url provided by django-allauth so user
    # is redirected to homepage instead of templateless inactive user
    re_path(
        r"^account/inactive/$",
        RedirectView.as_view(url=reverse_lazy("trapper_index")),
        name="account_inactive",
    ),
    # Trapper homepage
    re_path(r"^$", accounts_views.view_index, name="trapper_index"),
    # Media classification urls
    re_path(
        r"^media_classification/",
        include("trapper.apps.media_classification.urls", "media_classification"),
    ),
    # Research urls
    re_path(r"^research/", include("trapper.apps.research.urls")),
    # Storage urls
    re_path(r"^storage/", include("trapper.apps.storage.urls", "storage")),
    # Messaging urls
    re_path(r"^messaging/", include("trapper.apps.messaging.urls")),
    # Accounts urls
    re_path("", include("django.contrib.auth.urls")),
    re_path(r"^accounts/", include("trapper.apps.accounts.urls")),
    re_path(r"^account/", include("allauth.urls")),
    # GeoMap urls
    re_path(r"^geomap/", include("trapper.apps.geomap.urls")),
    # Comments
    re_path(r"^comments/", include("trapper.apps.comments.urls")),
    # Extra tables
    re_path(r"^tables/", include("trapper.apps.extra_tables.urls")),
    # Sendfile urls
    re_path(r"^serve/", include("trapper.apps.sendfile.urls")),
    re_path(r"^grappelli/", include("grappelli.urls")),
    re_path(r"^admin/", admin.site.urls),
    # REST API Swagger docs
    re_path(
        r"^docs/api/swagger(?P<format>\.json|\.yaml)$",
        swagger_schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    re_path(
        r"^docs/api/$",
        swagger_schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    re_path(
        r"^docs/api/redoc/$",
        swagger_schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
    # Debug Toolbar
    re_path(r"^__debug__/", include(debug_toolbar.urls)),
    # Tinymce
    path("tinymce/", include("tinymce.urls")),
    path("api/", include(api_patterns)),
    path("o/", include("oauth2_provider.urls", namespace="oauth2_provider")),
]

# Umap patterns
urlpatterns += (
    re_path(
        r"^map/(?P<pk>\d+)/geojson/$",
        umap_views.MapViewGeoJSON.as_view(),
        name="map_geojson",
    ),
    re_path(
        r"^map/anonymous-edit/(?P<signature>.+)$",
        umap_views.MapAnonymousEditUrl.as_view(),
        name="map_anonymous_edit_url",
    ),
    re_path(
        r"^pictogram/json/$",
        umap_views.PictogramJSONList.as_view(),
        name="pictogram_list_json",
    ),
    re_path(
        r"^$",
        accounts_views.view_index,
        name="user_dashboard",
    ),
)
urlpatterns += decorated_patterns(
    cache_control(must_revalidate=True),
    re_path(
        r"^datalayer/(?P<pk>[\d]+)/$",
        umap_views.DataLayerView.as_view(),
        name="datalayer_view",
    ),  # noqa
    re_path(
        r"^datalayer/(?P<pk>[\d]+)/versions/$",
        umap_views.DataLayerVersions.as_view(),
        name="datalayer_versions",
    ),  # noqa
    re_path(
        r"^datalayer/(?P<pk>[\d]+)/(?P<name>[_\w]+.geojson)$",
        umap_views.DataLayerVersion.as_view(),
        name="datalayer_version",
    ),  # noqa
)
urlpatterns += decorated_patterns(
    [ensure_csrf_cookie],
    re_path(
        r"^map/(?P<slug>[-_\w]+)_(?P<pk>\d+)$", umap_views.MapView.as_view(), name="map"
    ),  # noqa
    re_path(r"^map/new/$", umap_views.MapNew.as_view(), name="map_new"),
)
urlpatterns += decorated_patterns(
    [login_required_if_not_anonymous_allowed, never_cache],
    re_path(r"^map/create/$", umap_views.MapCreate.as_view(), name="map_create"),
)
urlpatterns += decorated_patterns(
    [map_permissions_check, never_cache],
    re_path(
        r"^map/(?P<map_id>[\d]+)/update/settings/$",
        umap_views.MapUpdate.as_view(),
        name="map_update",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/update/permissions/$",
        umap_views.UpdateMapPermissions.as_view(),
        name="map_update_permissions",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/update/owner/$",
        umap_views.AttachAnonymousMap.as_view(),
        name="map_attach_owner",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/update/delete/$",
        umap_views.MapDelete.as_view(),
        name="map_delete",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/update/clone/$",
        umap_views.MapClone.as_view(),
        name="map_clone",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/datalayer/create/$",
        umap_views.DataLayerCreate.as_view(),
        name="datalayer_create",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/datalayer/update/(?P<pk>\d+)/$",
        umap_views.DataLayerUpdate.as_view(),
        name="datalayer_update",
    ),
    re_path(
        r"^map/(?P<map_id>[\d]+)/datalayer/delete/(?P<pk>\d+)/$",
        umap_views.DataLayerDelete.as_view(),
        name="datalayer_delete",
    ),
)
urlpatterns += i18n_patterns(
    re_path(
        r"^showcase/$",
        cache_page(24 * 60 * 60)(umap_views.showcase),
        name="maps_showcase",
    ),
    re_path(r"^search/$", umap_views.search, name="search"),
    re_path(r"^about/$", umap_views.about, name="about"),
    re_path(r"^user/(?P<username>.+)/$", umap_views.user_maps, name="user_maps"),
)

if settings.DEBUG:
    urlpatterns = (
        urlpatterns
        + []
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

if settings.SILK_ENABLED:
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/projects/change.html
{% extends "media_classification/index.html" %}

{% load common_tags %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block data_app %}classification::create{% endblock data_app %}
{% block ng_app %}ng-app="trapperGrid"{% endblock ng_app %}

{% block section_content %}
<div class="container">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">
	  {% if object %}{% trans "Update" %}{% else %}{% trans "Add" %}{% endif %} {% trans "classification project" %}
	</h2>
      </div>
      <form action="." class="panel-body" method="post">
        {% crispy form form.helper %}
        <fieldset>
          <button type="submit" class="btn btn-primary">
            {% if object %}{% trans "Update" %}{% else %}{% trans "Add" %}{% endif %} {% trans "classification project" %}
          </button>
        </fieldset>
      </form>
      <div class="hidden">
	<table class="table">
	  <thead>
	  </thead>
	  <tbody>
	    <tr id="dynamic-form-row-template">
              {% with projectrole_formset.empty_form as form_template %}
              <td>
		{{ form_template.id }}
		{{ form_template.user|as_crispy_field }}
              </td>
              <td>{{ form_template.name|as_crispy_field }}</td>
              <td>
		<button type="button" class="btn btn-danger btn-remove-row pull-right">
		  <span class="fa fa-remove"></span>
		</button>
              </td>
	      {% endwith %}
	    </tr>
	  </tbody>
	</table>
      </div>
    </div>
  </div>
</div>
{% endblock section_content %}

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/projects/detail.html
{% extends "media_classification/index.html" %}

{% load i18n common_tags %}

{% block data_app %}classification{% endblock %}
{% block ng_app %}ng-app="trapperGrid"{% endblock ng_app %}

{% block section_content %}

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">{% trans "Classification project" %}</h2>
        </div>	
        <div class="panel-body">
          <h2>{{ project.name }}</h2>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">{% trans "Research project" %}</h2>
        </div>
        <div class="panel-body">
          <h2>
            <span class="fa fa-flask"></span>
            <a href="{% url 'research:project_detail' pk=project.research_project.pk %}">
              {{ project.research_project.acronym }}
            </a>
          </h2>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">{% trans "Flags" %}</h2>
        </div>
        <div class="panel-body">
          <label class="control-label">{% trans "Sequences" %}:</label>
          <span class="label label-default">{{ project.enable_sequencing }}</span>
          <label class="control-label">{% trans "Status" %}:</label>
          <span class="label label-default">{{ project.get_status_display }}</span>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">{% trans "Actions" %}</h2>
        </div>
        <div class="panel-body" style="display: flex; gap: 1rem; flex-wrap: wrap;">
          {% if project.can_update %}
          <a href="{% url "media_classification:project_update" project.pk %}"
             class="btn btn-default" role="button">
            <span class="fa fa-pencil"></span> {% trans "Update" %}
          </a>
          <a href="{% url "media_classification:classification_import" project.pk %}"
             class="btn btn-default" role="button">
            <span class="fa fa-upload"></span> {% trans "Import results" %}
          </a>
          <a href="{% url "media_classification:classification_export" project.pk %}"
             class="btn btn-default" role="button">
            <span class="fa fa-download"></span> {% trans "Export results" %}
          </a>
          {% endif %}

          {% if project.is_project_admin and jupyter_hub_enabled %}
          <button
            id="open-notebook-btn"
            class="btn btn-default" role="button">
            <span class="fa fa-file-code-o" data-icon></span> {% trans "Open notebook" %}
          </button>
          {% csrf_token %}
          <div class="alert alert-danger" role="alert" id="notebook-error" style="display: none; flex: 1;">
          </div>
          <script>
            document.getElementById('open-notebook-btn').addEventListener('click', function(e) {
              e.preventDefault();
              document.getElementById('open-notebook-btn').disabled = true;
              const iconEl = document.querySelector('#open-notebook-btn [data-icon]');
              iconEl.classList.add('fa-spin', 'fa-cog');
              iconEl.classList.remove('fa-file-code-o');
              const url = "{% url 'media_classification:open_notebook' project.pk %}";
              const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
              document.getElementById('notebook-error').style.display = 'none';
              fetch(url, {
                method: 'POST',
                credentials: 'same-origin',
                headers: {
                  'X-CSRFToken': csrftoken
                }
              }).catch(response => {
                document.getElementById('notebook-error').style.display = 'block';
                document.getElementById('notebook-error').innerHTML = response;
              })
              .then(response => {
                if (!response.ok) {
                  document.getElementById('notebook-error').style.display = 'block';
                  response.json().then(data => {
                    document.getElementById('notebook-error').innerHTML = data.detail;
                  });
                } else {
                  response.json().then(data => {
                    const server_url = data.server_url;
                    console.log(server_url);
                    window.open(server_url, '_blank');
                  });
                }
              }).finally(() => {
                console.log('done');
                document.getElementById('open-notebook-btn').disabled = false;
                iconEl.classList.remove('fa-spin', 'fa-cog');
                iconEl.classList.add('fa-file-code-o');
              })
            });
          </script>
          {% endif %}
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">{% trans "Project results" %}</h2>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-6">
              <ul class="list-group list-group-rich">
                {% with project.get_classification_stats as stats %}
                <li class="list-group-item">
                  <span
		    title="Number of resources with user classifications (approved)">
		    {% trans "User classifications" %}:
		  </span>
                  <strong>
		    {{ stats.classified }} ({{ stats.approved }})
		  </strong>
                </li>
                <li class="list-group-item">
                  <span 
                    title="Number of resources with AI classification (approved)">
		    {% trans "AI classifications" %}:
		  </span>
                  <strong>
		    {{ stats.classified_ai }} ({{ stats.approved_ai }})
		  </strong>
                </li>
                <li class="list-group-item">
                  <span 
                    title="Number of resources without classification">
		    {% trans "Unclassified" %}:</span>
                  <strong>
		    {{ stats.unclassified }}
		  </strong>
                </li>
                {% endwith %}
              </ul>
            </div>
	    {% if project.can_view_classifications %}
            <div class="col-md-4">
              <div class="row">
                <div class="col-md-12" style="padding: 2px">
                  <a
		    href="{% url 'media_classification:classification_list' pk=project.pk %}"
                    class="btn btn-success btn-block"
		    style="text-align: left">
                    <i class="fa fa-eye" style="margin-right: 5px"></i> {% trans "Classification results" %}
                  </a>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12"  style="padding: 2px">
                  <a
		    href="{% url 'media_classification:ai_classification_list' project_id=project.pk %}"
                    class="btn btn-primary btn-block" style="text-align: left">
                    <i class="fa fa-eye" style="margin-right: 5px"></i> {% trans "AI Classifications" %}
                  </a>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12"  style="padding: 2px">
                  <a
		    href="{% url 'media_classification:user_classification_list' pk=project.pk %}"
                    class="btn btn-success btn-block"
		    style="text-align: left">
                    <i class="fa fa-eye" style="margin-right: 5px"></i> {% trans "Users' classifications" %}
                  </a>
                </div>
              </div>
            </div>
	    {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading collapsable">
      <h2 class="panel-title">{% trans "Users in the project" %}</h2>
    </div>
    {% with project.get_user_roles_with_profiles as project_roles %}
    {% if project_roles %}
    <table class="table table-striped table-rich">
      <thead>
        <tr>
          <th></th>
          <th>{% trans "User" %}</th>
          <th>{% trans "Role" %}</th>
          <th>{% trans "E-mail" %}</th>
          <th>{% trans "Institution" %}</th>
        </tr>
      </thead>
      <tbody>
        {% for role in project_roles %}
        {% with role.user.userprofile as user_profile %}
        <tr>
          <td>
            <a href="{% url 'accounts:show_profile' role.user %}">
              <img src="{{ user_profile.avatar_url }}" alt="{{ role.user.username }}"
                   class="img-thumbnail avatar-small" style="display:inline">
            </a>
          </td>
          <td>
            <a href="{% url 'accounts:show_profile' role.user %}">
	      {{ role.user|pretty_username }}
	    </a>
          </td>
          <td>{{ role.get_name_display }}</td>
          <td>
	    <a href="mailto:{{ role.user.email }}">
	      {{ role.user.email|default:"" }}
	    </a>
	  </td>
          <td>{{ user_profile.institution|default:"" }}</td>
          {% endwith %}
          {% endfor %}
      </tbody>
    </table>
    {% endif %}
    {% endwith %}
  </div>
</div>

<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="panel-title">{% trans "Classificator" %}</h2>
    </div>
    <div class="panel-body">
      {% if project.classificator %}
      <a href="{% url 'media_classification:classificator_detail' pk=project.classificator.pk %}">{{ project.classificator.name }}</a>
      {% else %}
      There is no classificator assigned to this project.
      {% endif %}
    </div>
  </div>
</div>

<h2 class="container">{% trans "Collections" %}</h2>
{% with grid_context=collection_context %}
{% include 'media_classification/projects/detail_collection_grid.html' %}
{% endwith %}

{% endblock section_content %}

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/projects/form_inline.html
{% load i18n %}

<div class="form-inline">

    <div class="checkbox-inline">
        <label>
            {{ form.deployment_based_nav }}
            {% trans "Deployment-based navigation" %}
        </label>
    </div>

    <div class="checkbox-inline">
        <label>
            {{ form.enable_sequencing }}
            {% trans "Sequences" %}
        </label>
    </div>

    <div class="checkbox-inline">
        <label>
            {{ form.enable_crowdsourcing }}
            {% trans "Crowdsourcing" %}
        </label>
    </div>

</div>